version: "3"
services:
  es:
    image: elasticsearch:7.17.0
    container_name: es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s -f es:9200/_cat/health >/dev/null || exit 1
    networks:
      - morphnet

  mysql:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=morphpass1
      - MYSQL_DATABASE=morpheus
      - MYSQL_INITDB_SKIP_TZINFO=true
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=$$MYSQL_ROOT_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
    networks:
      - morphnet

  rmq:
    image: rabbitmq:3.9
    container_name: rmq
    volumes:
      - ./rmqconfig/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rmqdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics ping || exit 1
    networks:
      - morphnet

  guacd:
    image: guacamole/guacd:1.5.1
    container_name: guacd
    networks:
      - morphnet

  morpheus:
    image: ghcr.io/tryfan/morpheus:latest
    container_name: morpheus
    environment:
      - MORPHEUS_APPLIANCE_URL=https://localhost
      - MORPHEUS_ELASTICSEARCH_ES_HOSTS={'es' => 9200}
      #- MORPHEUS_MYSQL_HOST={'mysql' => 3306}
      - MORPHEUS_MYSQL_MORPHEUS_DB_USER=root
      - MORPHEUS_MYSQL_MORPHEUS_DB=morpheus
      - MORPHEUS_MYSQL_MORPHEUS_PASSWORD=morphpass1
      - MORPHEUS_MYSQL_MYSQL_URL_OVERIDE="jdbc:mysql://mysql:3306/morpheus?autoReconnect=true&useUnicode=true&characterEncoding=utf8&failOverReadOnly=false&useSSL=false&allowPublicKeyRetrieval=true"
      - MORPHEUS_RABBITMQ_HOST=rmq
      - MORPHEUS_RABBITMQ_VHOST=/
      - MORPHEUS_RABBITMQ_QUEUE_USER=morpheus
      - MORPHEUS_RABBITMQ_QUEUE_USER_PASSWORD=morphpass1
      - MORPHEUS_UI_LOG_DIR=/var/logs/morpheus
      - MORPHEUS_UI_MAX_MEMORY_MB=3584
    ports:
      - 443:443
    volumes:
      - ./morphdata:/var/opt/morpheus
      - ./morphlogs:/var/logs/morpheus
    depends_on:
      es:
        condition: service_healthy
      mysql:
        condition: service_healthy
      rmq:
        condition: service_healthy
    healthcheck:
      test: curl -qk https://localhost/ping | grep "MORPHEUS PING"
    networks:
      - morphnet

networks:
  morphnet: {}
